# Generated by Django 6.0.2 on 2026-02-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.IntegerField()),
                ('row', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('national_dex_number', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('image_url', models.URLField(blank=True, max_length=512)),
                ('games', models.CharField(blank=True, max_length=256)),
                ('notes', models.TextField(blank=True)),
                ('caught', models.BooleanField(default=False)),
                ('section', models.CharField(choices=[('living_dex', 'Living Dex'), ('gender_forms', 'Gender Variants & Forms'), ('stars', 'Stars'), ('shiny_living_dex', 'Shiny Living Dex'), ('shiny_gender_forms', 'Shiny Gender Variants & Forms')], max_length=32)),
                ('sort_order', models.IntegerField(default=0)),
                ('star_difficulty', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dex entries',
                'ordering': ['section', 'sort_order', 'box', 'row', 'slot'],
            },
        ),
    ]
