# Generated by Django 6.0.2 on 2026-02-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquareChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_id', models.PositiveIntegerField(unique=True)),
                ('option', models.PositiveSmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['square_id'],
            },
        ),
    ]
